apiVersion: apps/v1  # Version de l'API Kubernetes utilisée pour cette configuration
kind: StatefulSet  # Type de ressource Kubernetes à créer, ici un StatefulSet
metadata:  # Métadonnées pour la ressource
  name: mongo  # Nom du StatefulSet
  namespace: devops-demo  # Namespace dans lequel ce StatefulSet sera créé
spec:  # Spécifications du StatefulSet
  serviceName: "mongo-service"  # Nom du service associé à ce StatefulSet
  replicas: 1  # Nombre de réplicas (instances) du pod MongoDB
  selector:  # Sélecteur pour identifier les pods gérés par ce StatefulSet
    matchLabels:  # Critères de correspondance des étiquettes
      app: mongo  # Label utilisé pour sélectionner les pods
  template:  # Template pour les pods
    metadata:  # Métadonnées pour les pods
      labels:  # Labels appliqués aux pods
        app: mongo  # Label pour identifier les pods MongoDB
    spec:  # Spécifications des pods
      containers:  # Définition des conteneurs dans les pods
        - name: mongo  # Nom du conteneur
          image: mongo:latest  # Image Docker utilisée pour ce conteneur
          resources:  # Spécification des ressources
            requests:  # Ressources minimales demandées
              memory: 128Mi  # Mémoire demandée
              cpu: 100m  # CPU demandé
            limits:  # Limites maximales des ressources
              memory: 256Mi  # Mémoire maximale autorisée
              cpu: 200m  # CPU maximale autorisée
          env:  # Variables d'environnement
            - name: MONGO_INITDB_ROOT_USERNAME  # Nom d'utilisateur MongoDB
              valueFrom:  # Valeur obtenue depuis un Secret
                secretKeyRef:  # Référence au Secret
                  name: mongo-credentials  # Nom du Secret
                  key: username  # Clé dans le Secret
            - name: MONGO_INITDB_ROOT_PASSWORD  # Mot de passe MongoDB
              valueFrom:  # Valeur obtenue depuis un Secret
                secretKeyRef:  # Référence au Secret
                  name: mongo-credentials  # Nom du Secret
                  key: password  # Clé dans le Secret
          ports:  # Ports exposés par le conteneur
            - containerPort: 27017  # Port MongoDB
          volumeMounts:  # Points de montage des volumes
            - name: mongo-persistent-storage  # Nom du volume pour le stockage persistant
              mountPath: /data/db  # Chemin de montage dans le conteneur
            - name: init-script  # Nom du volume pour le script d'initialisation
              mountPath: /docker-entrypoint-initdb.d/init.js  # Chemin de montage dans le conteneur
              subPath: init.js  # Sous-chemin du volume monté
      volumes:  # Définition des volumes
        - name: mongo-persistent-storage  # Nom du volume pour le stockage persistant
          persistentVolumeClaim:  # Référence à un PersistentVolumeClaim
            claimName: mongo-persistent-storage  # Nom du PersistentVolumeClaim
        - name: init-script  # Nom du volume pour le script d'initialisation
          configMap:  # Référence à un ConfigMap
            name: mongo-init-script  # Nom du ConfigMap